### ISSUE TITLE
spotbugs-annotation.jar missing from spotbugs-4.0.0-RC1 bundle

### ISSUE THREAD

**Issue by eant60** [spotbugs/spotbugs#1066]
The bundle zip/tgz for spotbugs-4.0.0-RC1 is missing the spotbugs-annotation.jar dependency.  I can manually get the missing jar from the maven repository and fix the issue.

(I am a casual user of the command-line tool for my personal/simple projects, where I do not need or want to use the maven or similar build frameworks.  Consequently I prefer to use the spotbugs command-line tools and update via the spotbug tgz/zip bundles.)

$ diff -r -q spotbugs-4.0.0-RC1 spotbugs-4.0.0-beta4 
Only in spotbugs-4.0.0-beta4/lib: asm-7.1.jar
Only in spotbugs-4.0.0-RC1/lib: asm-7.3.1.jar
Only in spotbugs-4.0.0-beta4/lib: asm-analysis-7.1.jar
Only in spotbugs-4.0.0-RC1/lib: asm-analysis-7.3.1.jar
Only in spotbugs-4.0.0-beta4/lib: asm-commons-7.1.jar
Only in spotbugs-4.0.0-RC1/lib: asm-commons-7.3.1.jar
Only in spotbugs-4.0.0-beta4/lib: asm-tree-7.1.jar
Only in spotbugs-4.0.0-RC1/lib: asm-tree-7.3.1.jar
Only in spotbugs-4.0.0-beta4/lib: asm-util-7.1.jar
Only in spotbugs-4.0.0-RC1/lib: asm-util-7.3.1.jar
Only in spotbugs-4.0.0-beta4/lib: bcel-6.3.1.jar
Only in spotbugs-4.0.0-RC1/lib: bcel-6.4.1.jar
Only in spotbugs-4.0.0-RC1/lib: edu
Only in spotbugs-4.0.0-beta4/lib: spotbugs-annotations.jar
Files spotbugs-4.0.0-RC1/lib/spotbugs-ant.jar and spotbugs-4.0.0-beta4/lib/spotbugs-ant.jar differ
Files spotbugs-4.0.0-RC1/lib/spotbugs.jar and spotbugs-4.0.0-beta4/lib/spotbugs.jar differ

============================
doing SpotBugs spotbugs-4.0.0-RC1 on [--redacted--] with params: -longBugCodes -exclude custom_spotbugs/excludes.xml -low
============================
Exception in thread "main" java.lang.RuntimeException: Could not instantiate edu.umd.cs.findbugs.detect.BuildObligationPolicyDatabase as Detector2
	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:95)
	at edu.umd.cs.findbugs.DetectorFactory.createDetector2(DetectorFactory.java:396)
	at edu.umd.cs.findbugs.plan.AnalysisPass.instantiateDetector2sInPass(AnalysisPass.java:132)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1024)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:93)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: edu/umd/cs/findbugs/annotations/CleanupObligation
	at edu.umd.cs.findbugs.detect.BuildObligationPolicyDatabase.<init>(BuildObligationPolicyDatabase.java:138)
	... 14 more
Caused by: java.lang.ClassNotFoundException: edu.umd.cs.findbugs.annotations.CleanupObligation
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

**Comment by KengoTODA** [comment]
RC1 is unstable and old, please use stable version instead.
