### ISSUE TITLE
Invalid XML in spotbugs-4.0.2.jar messages.xml? (according to dom4j 2.1.3)

### ISSUE THREAD

**Issue by vorburger** [spotbugs/spotbugs#1128]
https://issues.apache.org/jira/browse/FINERACT-966

https://github.com/apache/fineract/pull/878

https://travis-ci.org/github/apache/fineract/builds/685174249

```
> Task :spotbugsIntegrationTest

edu.umd.cs.findbugs.PluginException: Couldn't parse "jar:file:/home/travis/.gradle/caches/modules-2/files-2.1/com.github.spotbugs/spotbugs/4.0.2/42afa23a07f27fa03d3b70f586fafbaae3391c02/spotbugs-4.0.2.jar!/messages.xml"
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1288)
	at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
	at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:353)
	at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:77)
	at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:60)
	at edu.umd.cs.findbugs.DetectorFactoryCollection.<clinit>(DetectorFactoryCollection.java:57)
	at com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:84)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:42)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:42)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:136)
	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.dom4j.DocumentException: arraycopy: last destination index 1275 out of bounds for char[1024]
	at org.dom4j.io.SAXReader.read(SAXReader.java:513)
	at org.dom4j.io.SAXReader.read(SAXReader.java:408)
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1285)
	... 38 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 1275 out of bounds for char[1024]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.gjt.xpp.impl.tokenizer.Tokenizer.next(Tokenizer.java:1274)
	at org.gjt.xpp.impl.pullparser.PullParser.next(PullParser.java:392)
	at org.gjt.xpp.sax2.Driver.parseSubTree(Driver.java:415)
	at org.gjt.xpp.sax2.Driver.parse(Driver.java:310)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 40 more
```

**Comment by vorburger** [comment]
Noted #1126 and #1122 but be that as it may, it still shouldn't choke on that XML?

**Comment by KengoTODA** [comment]
Plz make sure your project doesn't depend on `xpp3:xpp3`.
This is the module triggering your exception.

**Comment by vorburger** [comment]
Confirming that excluding xpp3 seems to fix this.

**Comment by vorburger** [comment]
see https://github.com/apache/fineract/pull/947/files

**Comment by andrijaperovic** [comment]
@KengoTODA confirmed that this issue persists even after removing `xpp3` module, are there any other libraries or transitive dependencies which need to be excluded? 

`
> Task :common:spotbugsMain FAILED
edu.umd.cs.findbugs.PluginException: Couldn't parse "jar:file:~/.gradle/caches/modules-2/files-2.1/com.github.spotbugs/spotbugs/4.0.2/42afa23a07f27fa03d3b70f586fafbaae3391c02/spotbugs-4.0.2.jar!/messages.xml"
        at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1288)
        at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
        at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
        at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
        at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
        at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
        at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
        at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:353)
        at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:77)
        at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:60)
        at edu.umd.cs.findbugs.DetectorFactoryCollection.<clinit>(DetectorFactoryCollection.java:57)
        at com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor.execute(SpotBugsRunnerForWorker.java:90)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.dom4j.DocumentException
        at org.dom4j.io.SAXReader.read(SAXReader.java:513)
        at org.dom4j.io.SAXReader.read(SAXReader.java:408)
        at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1285)
        ... 38 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.base/java.lang.System.arraycopy(Native Method)
        at org.gjt.xpp.impl.tokenizer.Tokenizer.next(Tokenizer.java:1274)
        at org.gjt.xpp.impl.pullparser.PullParser.next(PullParser.java:392)
        at org.gjt.xpp.sax2.Driver.parseSubTree(Driver.java:415)
        at org.gjt.xpp.sax2.Driver.parse(Driver.java:310)
        at org.dom4j.io.SAXReader.read(SAXReader.java:494)
        ... 40 more
`

**Comment by KengoTODA** [comment]
It depends on your CLASSPATH, please provide a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to debug.

**Comment by andrijaperovic** [comment]
Hi @KengoTODA , I will work on an mcve to reproduce the issue. 
In the meantime, here is the buildscript classpath:

```
Buildscript classpath: ~/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/67.1/2e159807158095566726600534034030dddab6d0/icu4j-67.1.jar:~/.gradle/caches/modules-2/files-2.1/org.dom4j/dom4j/2.1.3/a75914155a9f5808963170ec20653668a2ffd2fd/dom4j-2.1.3.jar:~/.gradle/caches/modules-2/files-2.1/jaxen/jaxen/1.1.6/3f8c36d9a0578e8e98f030c662b69888b1430ac0/jaxen-1.1.6.jar:~/.gradle/caches/modules-2/files-2.1/javax.xml.stream/stax-api/1.0-2/d6337b0de8b25e53e81b922352fbea9f9f57ba0b/stax-api-1.0-2.jar:~/.gradle/caches/modules-2/files-2.1/net.java.dev.msv/xsdlib/2013.6.1/280f7c45aaec5102cc756d1afdb416b7775f2ef4/xsdlib-2013.6.1.jar:~/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.2.12/4c83805595b15acf41d71d49e3add7c0e85baaed/jaxb-api-2.2.12.jar:~/.gradle/caches/modules-2/files-2.1/pull-parser/pull-parser/2/c2f040085bfcd35963e9504bec11dac57cd0a86e/pull-parser-2.jar:~/.gradle/caches/modules-2/files-2.1/xpp3/xpp3/1.1.4c/9b988ea84b9e4e9f1874e390ce099b8ac12cfff5/xpp3-1.1.4c.jar:~/.gradle/caches/modules-2/files-2.1/relaxngDatatype/relaxngDatatype/20020414/de7952cecd05b65e0e4370cc93fc03035175eef5/relaxngDatatype-20020414.jar
```
Thank you for your help.
