### ISSUE TITLE
e.u.c.f.b.AnalysisException after upgrade of SB from 4.0.4 to 4.0.5 in maven project

### ISSUE THREAD

**Issue by pzygielo** [spotbugs/spotbugs#1176]
```
[INFO] --- spotbugs-maven-plugin:4.0.4:spotbugs (default-cli) @ api ---
[INFO] Fork Value is true
     [java] Exception in thread "main" edu.umd.cs.findbugs.ba.AnalysisException: Exeption was thrown during analysis
     [java] 	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1125)
     [java] 	at java.util.ArrayList.forEach(ArrayList.java:1257)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java] Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: frame_type field doesn't exist
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1120)
     [java] 	... 5 more
     [java] Caused by: java.lang.AssertionError: frame_type field doesn't exist
     [java] 	at edu.umd.cs.findbugs.StackMapAnalyzer.lambda$static$0(StackMapAnalyzer.java:150)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at edu.umd.cs.findbugs.StackMapAnalyzer.<clinit>(StackMapAnalyzer.java:142)
     [java] 	at edu.umd.cs.findbugs.StackMapAnalyzer$StackMapAnalysisFactory.analyze(StackMapAnalyzer.java:66)
     [java] 	at edu.umd.cs.findbugs.StackMapAnalyzer$StackMapAnalysisFactory.analyze(StackMapAnalyzer.java:58)
     [java] 	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:368)
     [java] 	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:321)
     [java] 	at edu.umd.cs.findbugs.OpcodeStack.getJumpInfoFromStackMap(OpcodeStack.java:3075)
     [java] 	at edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:3030)
     [java] 	at com.mebigfatguy.fbcontrib.collect.CollectStatistics.visitCode(CollectStatistics.java:140)
     [java] 	at org.apache.bcel.classfile.Code.accept(Code.java:131)
     [java] 	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
     [java] 	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:397)
     [java] 	at org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
     [java] 	at edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java] 	at com.mebigfatguy.fbcontrib.collect.CollectStatistics.visitClassContext(CollectStatistics.java:108)
     [java] 	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.lambda$null$1(FindBugs2.java:1108)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
     [java] 	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238)
```
Project uses
```xml
                            <plugin>
                                <groupId>com.mebigfatguy.sb-contrib</groupId>
                                <artifactId>sb-contrib</artifactId>
                                <version>7.4.7</version>
                            </plugin>
```
as I see
```
     [java] 	at com.mebigfatguy.fbcontrib.collect.CollectStatistics.visitCode(CollectStatistics.java:140)
```
in above log, but it was working fine with 4.0.4 (ie. spotbugs upgrade is the only changed piece that triggers `AnalysisException`).
Given https://github.com/spotbugs/spotbugs/blob/4.0.5/CHANGELOG.md and claim to follow semantic versioning I find this exception a bit surprising.
I see there was
```
-  api 'org.apache.bcel:bcel:6.4.1'
+  api 'org.apache.bcel:bcel:6.5.0'
```
between 4.0.4 and 4.0.5, and bcel also participates in trace.

No separate reproducer at the moment, but I can work on one if the cause isn't obvious and one is needed.

**Comment by pzygielo** [comment]
> Especially when you report a problem, make sure you share [a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) to reproduce it in this issue.

Mr. Robot, if you insist here it is:
- [spotbugs-1176-AnalysisException](https://github.com/pzrep/spotbugs-1176-AnalysisException)

with master at SB:4.0.4 passing build and [with SB updated to 4.0.5](https://github.com/pzrep/spotbugs-1176-AnalysisException/tree/update-sb) that fails with [trace](https://github.com/pzrep/spotbugs-1176-AnalysisException/runs/792298579?check_suite_focus=true#step:4:1250) as above.

**Comment by pzygielo** [comment]
Not sure, but found this change https://github.com/apache/commons-bcel/commit/7e5355a1eb85940ada6a6bf81258dc9c23211f56 in bcel between 6.4.1 and 6.5.0.

**Comment by pzygielo** [comment]
Proposed #1177, but I'm pretty sure SB deserves some new test around this to avoid similar case in the future.
