### ISSUE TITLE
Problem running SpotBugs when debugging in eclipsePlugin

### ISSUE THREAD

**Issue by YinZho** [spotbugs/spotbugs#1295]
Hi, @KengoTODA

The process is attached as below:

Open Eclipse Application (Follow the instruction from [building_spotbugs_plugin.txt](https://github.com/spotbugs/spotbugs/blob/master/eclipsePlugin/doc/building_spotbugs_plugin.txt)) | Right Click eclipsePlugin Project | Run as Eclipse Application | Waiting for a new Eclipse window open

On the new Eclipse Window 
Import any existing project | Right-click the project | SpotBugs | Find bugs

The problem exists:
![image](https://user-images.githubusercontent.com/26624606/93671952-9ef62480-fad9-11ea-9a2c-650b76dd926c.png)

The whole log info also has been attached below.
[log.txt](https://github.com/spotbugs/spotbugs/files/5250193/log.txt)

Main exception:
```
!ENTRY org.eclipse.ui 4 4 2020-09-20 00:50:54.647
!MESSAGE Could not create action delegate for id: de.tobject.findbugs.findBugs
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2020-09-20 00:50:54.647
!MESSAGE Plug-in com.github.spotbugs.plugin.eclipse was unable to load class de.tobject.findbugs.actions.FindBugsAction.
!STACK 0
java.lang.ClassNotFoundException: de.tobject.findbugs.actions.FindBugsAction cannot be found by com.github.spotbugs.plugin.eclipse_4.1.3.202009191946-a11965a
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:287)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:285)
	at org.eclipse.ui.internal.PluginAction.createDelegate(PluginAction.java:126)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:214)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by YinZho** [comment]
The build results:
```
(base) ➜  /Users/zhouying/git/spotbugs (master) ✔ ./gradlew clean build

> Configure project :spotbugs-annotations
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs-ant
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-core
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-jupiter
The signing key and password are null. This can be ignored if this is a pull request.

> Task :spotbugs-annotations:compileJava
Note: /Users/zhouying/git/spotbugs/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/OverrideMustInvoke.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :spotbugs:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :spotbugs:compileGuiJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :eclipsePlugin:compileJava
/Users/zhouying/git/spotbugs/eclipsePlugin/src/de/tobject/findbugs/properties/FindbugsPropertyPage.java:300: warning: non-varargs call of varargs method with inexact argument type for last parameter;
        effortViewer.add(Effort.values());
                                      ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :eclipsePlugin:testPluginJar
Eclipse plugin contains spotbugs.jar

> Task :eclipsePlugin:generateCandidateP2Metadata FAILED
to sign eclipse plugins, set "keystorepass" project property
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':eclipsePlugin:generateCandidateP2Metadata'.
> A problem occurred starting process 'command '/Users/zhouying/git/Eclipse46/eclipse''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
34 actionable tasks: 31 executed, 3 up-to-date
```


```
(base) ➜  /Users/zhouying/git/spotbugs (master) ✔ ./gradlew eclipse

> Configure project :spotbugs-annotations
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :spotbugs-ant
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-core
The signing key and password are null. This can be ignored if this is a pull request.

> Configure project :test-harness-jupiter
The signing key and password are null. This can be ignored if this is a pull request.

BUILD SUCCESSFUL in 1s
83 actionable tasks: 66 executed, 17 up-to-date

**Comment by YinZho** [comment]
And I also reproduce both on Ubuntu 18.04 and macOS. So I think it is a common problem.
![image](https://user-images.githubusercontent.com/26624606/93716690-d7facb80-fba3-11ea-8af7-a89255a118ff.png)

**Comment by nmtbr1001** [comment]
”| Right Click eclipsePlugin Project | Run as Eclipse Application | Waiting for a new Eclipse window open

On the new Eclipse Window:
Import any existing project | Right-click the project | SpotBugs | Find bugs ”

Is it possible to find vulnerabilities in the source code?

![質問](https://user-images.githubusercontent.com/66873169/94703269-a212cf80-0379-11eb-8217-562cc979a16b.png)

I also want to develop a plugin for Spotbugs.
Is the tool for finding vulnerabilities in C: \ Users \ 81804 \ git \ spotbugs \ eclipsePlugin?

**Comment by YinZho** [comment]
@nmtbr1001 It will find vulnerabilities in your project 'abc'
