### ISSUE TITLE
Terminating Spotbugs jobs in Eclipse results in an error dialog

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#1314]
Since some 4.0.x builds I'm observing the problem, that termitating the Spotbugs job running in Eclipse results in an error dialog. That was not the case before, it is a regression.

Below stack from 4.18 Eclipse running Spotbugs head, but same problem can be observed in 4.15 and older Spotbugs version SpotBugs	4.0.1.r202003180840-6f24e9b.

```
eclipse.buildId=4.18.0.I20200928-1800
java.version=11.0.8
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

org.eclipse.core.jobs
Error
Tue Sep 29 10:23:16 CEST 2020
An internal error occurred during: "Finding bugs in eclipsePlugin...".

edu.umd.cs.findbugs.ba.AnalysisException: Exeption was thrown during analysis
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1125)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:313)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:219)
	at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:275)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.ExecutionException: java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1120)
	... 8 more
Caused by: java.lang.InterruptedException
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1100)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
	at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
	... 7 more
```

**Comment by iloveeclipse** [comment]
This is regression from #972 changes. I will push a patch shortly.

**Comment by iloveeclipse** [comment]
Verified works with plugin version 4.1.4.202010061816-5fc27ac
