### ISSUE TITLE
eclipse gradle target tests fail with Eclipse I20200928

### ISSUE THREAD

**Issue by trancexpress** [spotbugs/spotbugs#1322]
When running `./gradlew build eclipse` with target Eclipse:

Eclipse SDK
Version: 2020-12 (4.18)
Build id: I20200928-1800

I see errors:

```
> Task :eclipsePlugin-junit:test

de.tobject.findbugs.reporter.ThrottledProgressMonitorTest > testSetTaskName FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: interface org.eclipse.core.runtime.IProgressMonitor.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 11
    JVM vendor name    : Oracle Corporation
    JVM vendor version : 11.0.8+10-LTS
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 11.0.8+10-LTS
    JVM info           : mixed mode, sharing
    OS name            : Linux
    OS version         : 3.10.0-862.3.2.el7.x86_64


    Underlying exception : java.lang.IllegalArgumentException: Could not create type
        at de.tobject.findbugs.reporter.ThrottledProgressMonitorTest.testSetTaskName(ThrottledProgressMonitorTest.java:14)

        Caused by:
        java.lang.IllegalArgumentException: Could not create type
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:350)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:361)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:29)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:52)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
            at org.mockito.Mockito.spy(Mockito.java:2068)
            ... 1 more

            Caused by:
            java.lang.NoSuchMethodError: 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder.appendMostSpecific(java.util.Collection)'
                at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:89)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
                at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
                ... 11 more

de.tobject.findbugs.reporter.ThrottledProgressMonitorTest > testWorked FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: interface org.eclipse.core.runtime.IProgressMonitor.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 11
    JVM vendor name    : Oracle Corporation
    JVM vendor version : 11.0.8+10-LTS
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 11.0.8+10-LTS
    JVM info           : mixed mode, sharing
    OS name            : Linux
    OS version         : 3.10.0-862.3.2.el7.x86_64


    Underlying exception : java.lang.IllegalArgumentException: Could not create type
        at de.tobject.findbugs.reporter.ThrottledProgressMonitorTest.testWorked(ThrottledProgressMonitorTest.java:31)

        Caused by:
        java.lang.IllegalArgumentException: Could not create type
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:350)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:361)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:29)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:52)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
            at org.mockito.Mockito.spy(Mockito.java:2068)
            ... 1 more

            Caused by:
            java.lang.NoSuchMethodError: 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder.appendMostSpecific(java.util.Collection)'
                at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:89)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
                at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
                ... 11 more

2 tests completed, 2 failed

> Task :eclipsePlugin-junit:test FAILED

FAILURE: Build failed with an exception.
```

**Comment by hazendaz** [comment]
old issue, closing, if still present, please show data with newer eclipse and version of plugin used.
