### ISSUE TITLE
SARIF output + unknown source filenames writes exceptions to stderr

### ISSUE THREAD

**Issue by dotpaul** [spotbugs/spotbugs#1412]
When there is a bug whose location is in an unknown source code filename, and outputting to SARIF, SpotBugs writes an exception to stderr.

Here's an example:

```
java.net.URISyntaxException: Illegal character in path at index 15: org/hsqldb/lib/<Unknown>
        at java.base/java.net.URI$Parser.fail(URI.java:2936)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
        at java.base/java.net.URI$Parser.parse(URI.java:3148)
        at java.base/java.net.URI.<init>(URI.java:623)
        at edu.umd.cs.findbugs.sarif.Location$ArtifactLocation.fromBugAnnotation(Location.java:149)
        at edu.umd.cs.findbugs.sarif.Location$PhysicalLocation.fromBugAnnotation(Location.java:246)
        at edu.umd.cs.findbugs.sarif.Location.findPhysicalLocation(Location.java:90)
        at edu.umd.cs.findbugs.sarif.Location.fromBugInstance(Location.java:70)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.processResult(BugCollectionAnalyser.java:62)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.lambda$new$1(BugCollectionAnalyser.java:38)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.<init>(BugCollectionAnalyser.java:34)
        at edu.umd.cs.findbugs.sarif.SarifBugReporter.processRuns(SarifBugReporter.java:34)
        at edu.umd.cs.findbugs.sarif.SarifBugReporter.finish(SarifBugReporter.java:24)
        at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
        at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1165)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
        at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
        at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
```

**Comment by JuditKnoll** [comment]
This is still relevant in Spotbugs' current master, and also happens in several tests in `SarifBugReporterTest` ([src](https://github.com/spotbugs/spotbugs/blob/master/spotbugs-tests/src/test/java/edu/umd/cs/findbugs/sarif/SarifBugReporterTest.java)), e.g. `testInvocationSuccessfulOnBugPresence`.
