### ISSUE TITLE
Eclipse plugin: Not able to view bug details

### ISSUE THREAD

**Issue by daolaf** [spotbugs/spotbugs#147]
I have built and installed the eclipse plugin after uninstalling the FB plugin. I can not view bug details as an error is shown:

![grafik](https://cloud.githubusercontent.com/assets/23480263/23563031/48f0a548-0045-11e7-8afa-f3b5e319a9c9.png)

Call stack:
`java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:79)
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:64)
	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM$1.<init>(ClassParserUsingASM.java:519)
	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:519)
	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:699)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:79)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue.<init>(TypeQualifierValue.java:104)
	at edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue.getValue(TypeQualifierValue.java:304)
	at edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue.getValue(TypeQualifierValue.java:312)
	at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.<init>(TypeQualifierNullnessAnnotationDatabase.java:70)
	at edu.umd.cs.findbugs.ba.AnalysisContext.getNullnessAnnotationDatabase(AnalysisContext.java:1050)`

Happens for every bug I select in the bug explorer.

**Comment by KengoTODA** [comment]
Thanks @daolaf for your reporting. It's really strange to see this bug, because it cannot happen in theory.

* http://websvn.ow2.org/blame.php?repname=asm&path=%2Ftags%2FASM_6_0_ALPHA%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2FClassVisitor.java&rev=1827#l79
* https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/engine/asm/FindBugsASM.java#L29

Is it possible that you're using old ASM in Eclipse plugin?

**Comment by daolaf** [comment]
Turned out the stacktrace had nothing to do with the error. It was a leftover from an older run where I indeed had an older ASM version.

The actual problem seems to be simply that the UserAnnotationsView got removed completely (as it relates to the removed cloud stuff) as class and from the perspective. If I switch to the perspective on a new workspace everything works fine but on an existing workspace where the perspective got still saved with the view then this error appears. This makes the erorr non-critical but it is still not nice.

What could be done is to change the perspective ID to an own sputbugs ID instead of reusing the old findbug perspective ID.

**Comment by KengoTODA** [comment]
We've changed Eclipse plugin ID by #157

**Comment by iloveeclipse** [comment]
Works on master with #216 applied.

**Comment by iloveeclipse** [comment]
I think we can close this one.
