### ISSUE TITLE
Eclipse setup is wrong, cycle project dependencies

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#151]
I've tried to import spotbugs into Eclipse for the first time, this failed badly because a new "test-harness" project is added which is used by spotbugs but which also depends on it. Eclipse denies to compile both projects because of the cycle. Of course I can change compiler settings in Eclipse but why did we added this cycle at all???

This is a no-go.

The solution is to extract spotbugs tests code (src/test/java) from spotbugs project and place it under extra spotbugs-tests project. This was a mess before in findbugs but we should not keep this mess and increase the pain by adding cycles.

Just found out that even new gradlePlugin project continues with the bad habit to include everything in one place, resulting in another cycle. The test code under src/test/java belongs to the extra gradlePlugin-tests project.

**Comment by KengoTODA** [comment]
refs #108 for cyclic reference.

**Comment by iloveeclipse** [comment]
@KengoTODA : please check the commit above. Today I've tried to import spotbugs to understand Eclipse plugin issues but found out that current setup is broken on Eclipse. Also I'm not sure but it seems that the findbugs unit tests I've moved were not executed at all? Anyway, 3 of them seem to fail now because the new AnalysisRunner seem to be confused by an unexpected findbugs.xml location:
`
java.lang.ExceptionInInitializerError
	at edu.umd.cs.findbugs.test.SpotBugsRule.before(SpotBugsRule.java:52)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at edu.umd.cs.findbugs.test.AnalysisRunner.createTempJar(AnalysisRunner.java:146)
	at edu.umd.cs.findbugs.test.AnalysisRunner.<clinit>(AnalysisRunner.java:61)
	... 36 more
`

I have no gradle experience at all, so I somehow copy/pasted gradle build files together. I see 3 test failures caused by AnalysisRunner and I have no idea how to specify the right tests classpath so that AnalysisRunner can find findbugs.xml on a disk (and not inside jar).

**Comment by iloveeclipse** [comment]
I'm targeting this for 3.1.0, because broken projects setup in Eclipse make the code useless for me. I'm going to disable those 3 tests and push the change soon (unless someone has an idea how to fix the gradle test classpath), along with the #152 fixes.

**Comment by iloveeclipse** [comment]
Actually this is not the only issue blocking Eclipse plugin - see issue #153 which is a complete disaster. I was not aware that no one cared about Eclipse plugin, but for now it looks like spotbugs succeeded in destroying Eclipse plugin.
