### ISSUE TITLE
ExcludeFilter configuration failed.

### ISSUE THREAD

**Issue by YorkHwang** [spotbugs/spotbugs#1690]
ExcludeFilter configuration failed.

```
java.io.IOException: Content is not allowed in prolog.
	at edu.umd.cs.findbugs.filter.Filter.<init>(Filter.java:135)
	at edu.umd.cs.findbugs.FindBugs.configureFilter(FindBugs.java:471)
	at edu.umd.cs.findbugs.FindBugs2.addFilter(FindBugs2.java:404)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.configureFilter(FindBugsStarter.java:428)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:318)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:54)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KengoTODA** [comment]
Your XML file probably has some problem, refer to https://mkyong.com/java/sax-error-content-is-not-allowed-in-prolog/

**Comment by gtoison** [comment]
There was no answer or update so I'll assume this was indeed an invalid filter file, not a bug
Please open a new issue if the problem persists
