### ISSUE TITLE
Error reported while running Spotbugs under Java 17

### ISSUE THREAD

**Issue by Fernal73** [spotbugs/spotbugs#1790]
```[spotbugs] Running SpotBugs...         [spotbugs] Unexpected problem occured during version sanity check             [spotbugs] Reported exception:         [spotbugs] java.lang.AbstractMethodError: Receiver class org.slf4j.nop.NOPServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequesteApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.               [spotbugs]     at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:295)                                 [spotbugs]     at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:143)                              [spotbugs]     at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419) [spotbugs]     at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:405)                                  [spotbugs]     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:354)
 [spotbugs]     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:380)
 [spotbugs]     at edu.umd.cs.findbugs.FindBugs2.<clinit>(FindBugs2.java:96)
```

The above error is encountered while executing Spotbugs ant task under Java 17.

The build.xml is located at:

https://github.com/Fernal73/LearnJava/blob/master/Switch/build.xml

**Comment by KengoTODA** [comment]
I believe that it's not spotbugs issue nor java 17 problem. Refer to http://www.slf4j.org/faq.html#changesInVersion200 and make sure that SLF4J binding uses the same version with API.

**Comment by Fernal73** [comment]
Ok. That's fine. If I take out the slf4j providers which I added (and update as their versions change), I have the following message:

```
[spotbugs] Running SpotBugs...         [spotbugs] SLF4J: No SLF4J providers were found.                              [spotbugs] SLF4J: Defaulting to no-operation (NOP) logger implementation      [spotbugs] SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
```
which is why I added the providers earlier.
I guess one could live with this unless Spotbugs wishes to bundle providers with their jars.

Any unnecessary messages are irksome.

**Comment by KengoTODA** [comment]
According to https://mvnrepository.com/artifact/org.apache.ant/ant/1.10.12 Apache Ant does not have SLF4J binding in its classpath. Apache Ant provides [several loggers](https://ant.apache.org/manual/listeners.html), and custom tasks need to invoke logging methods in the [Project class](https://ant.apache.org/manual/api/org/apache/tools/ant/Project.html) to use these loggers.

We probably need to implement a simple SLF4J binding which delegates to the Project class provided by Apache Ant.

**Comment by L-keeey** [comment]
Hi @KengoTODA, @Fernal73  I would like to work on this issue.

**Comment by pushker001** [comment]
hey I am new here I would like to contribute here can you tell me how can I get started

**Comment by ThrawnCA** [comment]
> hey I am new here I would like to contribute here can you tell me how can I get started

Commenting on a random issue isn't really the right way to raise that. Starting a Discussion is more appropriate.

**Comment by sumanth-reddy13** [comment]
@KengoTODA Can I work on this issue?

**Comment by hazendaz** [comment]
Spotbugs uses log4j 2.  If a user wants to use slf4j, the need to provide the jars.  See the spotbugs maven plugin as i do just that.  Thus issue can be closed as it's not an issue with spotbugs nor ant.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
ok to explain further, the error indicates someone used slf4j api (spotbugs probably was that years ago) but failed to set an implementation.  They simply needed to add slf4j-simple to the classpath.  The noop occurs due to not doing that.  Since spotbugs is not using slf4j to start with and the errors are not related to spotbugs nor ant in the usage, just a configuration issue with classpath with how slf4j works, I don't think this is a valid issue here.

Now the issue as I see it here is that someone wants slf4j bundled with the product but since we are not using slf4j here, that would not apply.   My reference to the spotbugs maven plugin is that it does use slf4j entirely, its using ant via groovy to launch spotbugs, and it doesn't' have this issue.  Thus because its bundled with the plugin as the ask was here but since this project is not directly using slf4j, I'm not sure its applicable to just bundle libraries that users are introducing as seemed the case here.

@sumanth-reddy13 If you really want to look further at this, feel free to do so, all issues that exist are open to anyone to work against.  Just note what I mentioned above.  Maybe this issue exists with log4j2 usage, not sure.  If it does apply and is because of us, then certainly we should be bundling it but I'd also say users probably should be using one of the various build tools normally to execute spotbugs or understand they need to add all libraries they need.

**Comment by NehaPawar65** [comment]
Hi, I’m a beginner Java contributor and I’d like to work on this issue. Could you please assign it to me? Thanks!
