### ISSUE TITLE
java.lang.InterruptedException at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1100)

### ISSUE THREAD

**Issue by KushalP** [spotbugs/spotbugs#1891]
```
Product Infos
    SpotBugs: 4.4.2
    IntelliJ SpotBugs plugin: 1.2.5
    IDEA: IntelliJ IDEA 2021.3
    IDEA-Build: IU-213.5744.223, November 27, 2021
    JRE: 11.0.13+7-b1751.19 x86_64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

null
edu.umd.cs.findbugs.ba.AnalysisException: Exeption was thrown during analysis
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1125)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:326)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:54)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1120)
	... 28 more
Caused by: java.lang.InterruptedException
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1100)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
	at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
	... 27 more
```

**Comment by KengoTODA** [comment]
You intentionally interrupted, right? Then I think it's expected behavior...  

> An interrupt is an indication to a thread that it should stop what it is doing and do something else. It's up to the programmer to decide exactly how a thread responds to an interrupt, but it is very common for the thread to terminate.
> https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html

**Comment by hazendaz** [comment]
please check with intellij on their plugin as its out of support with us at this point.
