### ISSUE TITLE
Spotbugs can't be compiled against JDK 1.8

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#1906]
While reviewing #1902 I've found that SpotBugs that is supposed to be used on java 8 can't be compiled against Java 8, because it already uses Java 11 API. Specifying source 1.8 is not enough, if compiler uses Java 11 / 17 for Java class libraries used.

```
edu.umd.cs.findbugs.BugReporterDispatcherTest.dispatchingMethod():
The constructor PrintStream(ByteArrayOutputStream, boolean, Charset) is undefined
```

```
edu.umd.cs.findbugs.TextUICommandLineTest.htmlReportWithOption():
The method readString(Path, Charset) is undefined for the type Files
```

**Comment by iloveeclipse** [comment]
My proposal would be to bump spotbugs lower JDK requirement to Java 11. Since we haven't received bug reports yet, it means, most of the users are already using new JDK anyway. However, I'm unable to make gradle build happy because of spotbugs test cases that need to be compiled with 1.8 / 11 / 17 and gradle says that if consumer is compiled 1.8, the spotbugs itself must be also compiled with 1.8. Stupid!

**Comment by gtoison** [comment]
Currently the SonarQube LTS version (8.9) supports Java 8 and 11 while the latest version (9.2) only supports Java 11.
So bumping the lower JDK version required to 11 might be a problem for users of SonarQube 8.9 still on Java 8

**Comment by iloveeclipse** [comment]
OK, another possibility would be to:
- fix tests to use Java 8 API
- or move tests to separated project that can use Java 11+

**Comment by KengoTODA** [comment]
How do you think that we ask SpotBugs contributors to build the SpotBugs with JDK 11+?
Even though we use JDK 11+ to build, at least Gradle can generate class files that works on JVM 8, because we set `--release` option to realize it:

https://github.com/spotbugs/spotbugs/blob/fa0ef8ebb0c15edcd75b71d6b4218bafec6c3816/gradle/java.gradle#L10-L12

We may need additional work to configure Eclipse projects.

> fix tests to use Java 8 API

I think this is also nice option for us. It needs less changes than making another sub project.

**Comment by ThrawnCA** [comment]
The build also uses the `--add-exports` parameter, which is not compatible with JDK 8.

**Comment by KengoTODA** [comment]
> The build also uses the --add-exports parameter, which is not compatible with JDK 8.

Yes for Gradle. This parameter is not used when we build the project on Eclipse.

For Gradle, I've introduced JVM toolchain, which means that Gradle enforce developers to use Java 17 to build the project. So this issue #1906 is only for Eclipse projects generated by the `eclipse` task.

https://github.com/spotbugs/spotbugs/blob/e5ca94c62ebc6526ac7c6d449d9eee90925a1999/build.gradle#L27-L31

**Comment by iloveeclipse** [comment]
> It needs less changes than making another sub project.

We have **already** spotbugs-tests project. I wonder why do we have tests in two projects (core AND tests)???
I will try to move tests from core project to a dedicated tests project, I personally hate configurations where tests and code are in same project, because it always causes issues with wrong dependencies used etc.

**Comment by iloveeclipse** [comment]
@KengoTODA : please check https://github.com/spotbugs/spotbugs/tree/move_tests_to_tests branch.

That seem to be pretty straight forward change. 
Locally (on Java 11 / Windows) I see only 7 test fails in two tests, I assume something with the test setup is wrong (spotbugs seem to not find test class itself ?)

```
> Task :spotbugs-tests:test
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue (file:/C:/git/spotbugs/spotbugs/build/libs/spotbugs.jar)
WARNING: Please consider reporting this to the maintainers of edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by edu.umd.cs.findbugs.ba.jsr305.ValidationSecurityManagerTest (file:/C:/git/spotbugs/spotbugs-tests/build/classes/java/test/)
WARNING: Please consider reporting this to the maintainers of edu.umd.cs.findbugs.ba.jsr305.ValidationSecurityManagerTest

edu.umd.cs.findbugs.sarif.PlaceholderTest > testFormatWithKey FAILED
    java.lang.ClassNotFoundException: Exception while looking for class edu/umd/cs/findbugs/sarif/PlaceholderTest
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:94)
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:105)
        at org.apache.bcel.Repository.lookupClass(Repository.java:78)
        at edu.umd.cs.findbugs.sarif.PlaceholderTest.testFormatWithKey(PlaceholderTest.java:68)

        Caused by:
        edu.umd.cs.findbugs.classfile.MissingClassException: Resource not found: edu/umd/cs/findbugs/sarif/PlaceholderTest.class
            at app//edu.umd.cs.findbugs.classfile.engine.ClassDataAnalysisEngine.analyze(ClassDataAnalysisEngine.java:60)
            at app//edu.umd.cs.findbugs.classfile.engine.ClassDataAnalysisEngine.analyze(ClassDataAnalysisEngine.java:42)
            at app//edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
            at app//edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:57)
            at app//edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:42)
            at app//edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
            at app//edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
            ... 3 more

            Caused by:
            edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: edu/umd/cs/findbugs/sarif/PlaceholderTest.class
                at app//edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)
                at app//edu.umd.cs.findbugs.classfile.engine.ClassDataAnalysisEngine.analyze(ClassDataAnalysisEngine.java:53)
                ... 9 more

edu.umd.cs.findbugs.util.MutableClassesTest > TestMutable FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestMutable(MutableClassesTest.java:72)

edu.umd.cs.findbugs.util.MutableClassesTest > TestImmutable FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestImmutable(MutableClassesTest.java:102)

edu.umd.cs.findbugs.util.MutableClassesTest > TestImmutableValuedBased FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestImmutableValuedBased(MutableClassesTest.java:108)

edu.umd.cs.findbugs.util.MutableClassesTest > TestAnnotatedImmutable FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestAnnotatedImmutable(MutableClassesTest.java:51)

edu.umd.cs.findbugs.util.MutableClassesTest > TestErrorProneImmutable FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestErrorProneImmutable(MutableClassesTest.java:126)

edu.umd.cs.findbugs.util.MutableClassesTest > TestKnownMutable FAILED
    java.lang.NullPointerException: Cannot invoke "edu.umd.cs.findbugs.classfile.IAnalysisCache.getClassAnalysis(java.lang.Class, edu.umd.cs.findbugs.classfile.ClassDescriptor)" because the return value of "edu.umd.cs.findbugs.classfile.Global.getAnalysisCache()" is null
        at edu.umd.cs.findbugs.AnalysisCacheToRepositoryAdapter.loadClass(AnalysisCacheToRepositoryAdapter.java:92)
        at org.apache.bcel.Repository.lookupClass(Repository.java:65)
        at edu.umd.cs.findbugs.util.MutableClasses.mutableSignature(MutableClasses.java:72)
        at edu.umd.cs.findbugs.util.MutableClassesTest.TestKnownMutable(MutableClassesTest.java:25)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/C:/Users/Andrey/.gradle/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/lib/plugins/gradle-testing-base-7.3.3.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

352 tests completed, 7 failed, 3 skipped
```

**Comment by iloveeclipse** [comment]
What is interesting, the test failures above (same as in #1912) seem not be the classpath issue as seen by gradle vs Eclipse, it seem to be a test **environment** or test **isolation** issue. 
Executed **without** other build tasks running before / in parallel to the tests, they pass!
```
 ./gradlew :spotbugs-tests:test
```
So I assume some static cache in the related code could be the root cause, and running the tests in different order (before the offending task) would "fix" them.

The only problem is: 
- I have no idea which task that is executed before breaks the tests
- I have no idea how to force gradle to execute tests before that yet unknown task :-)

Simple solution would be to disable those tests for now.

**Comment by iloveeclipse** [comment]
OK, I've found an easy solution, will open a dedicated task to separate tests from code.
