### ISSUE TITLE
Runtime.getRuntime().exec oom

### ISSUE THREAD

**Issue by chongbo2013** [spotbugs/spotbugs#1981]
Runtime.getRuntime().exec("spotbugs -textui -low -xml=eport.xml -pluginList fb-contrib-7.4.7.jar -analyzeFromFile lottie.jar");

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at edu.umd.cs.findbugs.classfile.analysis.ClassInfo.computeMethodsInCallOrder(ClassInfo.java:243)
	at edu.umd.cs.findbugs.classfile.analysis.ClassInfo.<init>(ClassInfo.java:302)
	at edu.umd.cs.findbugs.classfile.analysis.ClassInfo.<init>(ClassInfo.java:58)
	at edu.umd.cs.findbugs.classfile.analysis.ClassInfo$Builder.build(ClassInfo.java:179)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:80)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
	at edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)

**Comment by KengoTODA** [comment]
Please share a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to help us to reproduce your problem in our local.

At least the implementation of `ClassInfo` class seems no problem:

https://github.com/spotbugs/spotbugs/blob/7c1ddfa09e416c1cf9175a26eb442f439b97fc30/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/analysis/ClassInfo.java#L243
