### ISSUE TITLE
unable to infer FindBugs version using gradle plugin 1.1

### ISSUE THREAD

**Issue by brharrington** [spotbugs/spotbugs#214]
I get an exception when trying the latest version of the gradle plugin:

```
Caused by: org.gradle.api.GradleException: Unable to infer the version of FindBugs from currently specified FindBugs classpath: [spotbugs-3.1.0-RC3.jar, asm-debug-all-6.0_ALPHA.jar, jcip-annotations-1.0.jar, dom4j-1.6.1.jar, commons-lang-2.6.jar, jaxen-1.1.6.jar, jdepend-2.9.1.jar, jFormatString-3.0.0.jar, spotbugs-annotations-3.1.0-RC3.jar, xml-apis-1.0.b2.jar, jsr305-3.0.1.jar]
        at com.github.spotbugs.internal.spotbugs.FindBugsClasspathValidator.getFindbugsVersion(FindBugsClasspathValidator.java:43)
        at com.github.spotbugs.internal.spotbugs.FindBugsClasspathValidator.validateClasspath(FindBugsClasspathValidator.java:19)
        at com.github.spotbugs.SpotBugsTask.run(SpotBugsTask.java:208)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
```

The [pattern](https://github.com/spotbugs/spotbugs/blob/master/gradlePlugin/src/main/java/com/github/spotbugs/internal/spotbugs/FindBugsClasspathValidator.java#L38) doesn't seem to match the spotbugs jars. It should be relatively easy to update the pattern, but the version matching will also need to change as it currently just expects numbers or dots. At the least it would also need to accept the `-RCN` suffix, but I'm not sure if there are others.

**Comment by KengoTODA** [comment]
@johnscancella Could you check?

**Comment by johnscancella** [comment]
@KengoTODA the reporter is correct, it is failing because it isn't looking for the spotbugs jar. I updated it to search for either spotbugs or findbugs jar and submitted a pull request.

**Comment by mbonness** [comment]
When I tried to migrate from FindBugs to SpotBugs today it gave me the same error.

`Caused by: org.gradle.api.GradleException: Unable to infer the version of FindBugs from currently specified FindBugs classpath: [spotbugs-3.1.3.jar, asm-commons-6.1.1.jar, asm-xml-6.1.1.jar, asm-util-6.1.1.jar, asm-analysis-6.1.1.jar, asm-tree-6.1.1.jar, asm-6.1.1.jar, bcel-6.2.jar, jcip-annotations-1.0.jar, dom4j-2.1.0.jar, jaxen-1.1.6.jar, commons-lang-2.6.jar, jFormatString-3.0.0.jar, spotbugs-annotations-3.1.3.jar, jsr305-3.0.2.jar]
        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsClasspathValidator.getFindbugsVersion(FindBugsClasspathValidator.java:57)
        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsClasspathValidator.validateClasspath(FindBugsClasspathValidator.java:35)
        at org.gradle.api.plugins.quality.FindBugs.run(FindBugs.java:231)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more`

w20682$ ./gradlew --version

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Mac OS X 10.12.6 x86_64

**Comment by johnscancella** [comment]
@mbonness what version of the plugin are you using?

**Comment by mbonness** [comment]
SpotBugs 3.1.3 for Gradle.  I was trying to follow the [migration instructions](http://spotbugs.readthedocs.io/en/latest/migration.html), but I think all I succeeded in doing was confuse the FindBugs plugin.

```
apply plugin: 'findbugs'

afterEvaluate {
    dependencies {
        findbugs 'com.github.spotbugs:spotbugs:3.1.3' // <-- don't do this
        findbugs configurations.findbugsPlugins.dependencies

        // Additional Findbugs plugins
        findbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.7.1'
        findbugsPlugins 'com.mebigfatguy.fb-contrib:fb-contrib:7.0.5'
        findbugsPlugins 'jp.f.dev.findbugs.detect.android:AndroidFindbugs:0.5'
    }
}
```

**Comment by johnscancella** [comment]
Oh now I understand you are using findbugs but trying to replace the jars with spotbugs. It is just easier to use the spotbugs plugin because it does that for you
see https://plugins.gradle.org/plugin/com.github.spotbugs
