### ISSUE TITLE
Running spotbugs 4.7.2 with -textui flag results in `org.apache.logging.slf4j.SLF4JServiceProvider` exception

### ISSUE THREAD

**Issue by creesch** [spotbugs/spotbugs#2176]
See the below output, this is with openJDK 11, the issue is not present in 4.7.1

```
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
	at edu.umd.cs.findbugs.CheckBcel.<clinit>(CheckBcel.java:40)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:99)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
```

**Comment by gtoison** [comment]
This is most likely since the upgrade to slf4j 2.0 in #2156 
Apparently there are some breaking changes between slf4j 1.x and 2.x
https://issues.apache.org/jira/browse/LOG4J2-3139

`getRequesteApiVersion` was renamed `getRequesteApiVersion` here:
https://github.com/qos-ch/slf4j/commit/7483a11dd6ba1398f4b51c2e673800325cc609fc

I think you need a log4j2 bridge compatible with slf4j 2 but I'm not it is released yet

**Comment by baloghadamsoftware** [comment]
I thought that the fault was in my system.
