### ISSUE TITLE
java.io.EOFException at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)

### ISSUE THREAD

**Issue by renatolean** [spotbugs/spotbugs#2359]
Product Infos
    SpotBugs: 4.4.2
    IntelliJ SpotBugs plugin: 1.2.5
    IDEA: IntelliJ IDEA 2022.3.2
    IDEA-Build: IU-223.8617.56, January 26, 2023
    JRE: 17.0.5+1-b653.25 aarch64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

null
java.io.IOException: IOException while scanning codebases
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:311)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:326)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:54)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$2.run(FindBugsStarter.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: edu.umd.cs.findbugs.classfile.InvalidClassFileFormatException: Invalid classfile format in /Users/xxxxx/Documents/workspace/java/service/target/test-classes/me/xxxxx/dataapi/data/IdentityApiIntegrationTest.class
	at edu.umd.cs.findbugs.classfile.engine.ClassParser.parse(ClassParser.java:144)
	at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBase.getClassDescriptor(SingleFileCodeBase.java:269)
	at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBaseEntry.getClassDescriptor(SingleFileCodeBaseEntry.java:82)
	at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:259)
	at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:708)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:245)
	... 25 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
	at edu.umd.cs.findbugs.classfile.engine.ClassParser.parse(ClassParser.java:90)
	... 30 more

**Comment by hazendaz** [comment]
@renatolean Do you have same issue if using more recent spotbugs (ie 4.7.3)?

**Comment by gtoison** [comment]
Hello @hazendaz 
Unless I misunderstood the [IntelliJ SpotBugs plugin](https://plugins.jetbrains.com/plugin/14014-spotbugs) is managed by Jetbrains [here](https://github.com/JetBrains/spotbugs-intellij-plugin) and seems to be "stuck" on SpotBugs 4.4.2 because the [PR to upgrade to 4.7.2](https://github.com/JetBrains/spotbugs-intellij-plugin/pull/982) failed

**Comment by hazendaz** [comment]
Module is a reserved key word in Java which the error is stating.  Assuming used jdk too high to build.  Use java 8 or change jet brains code to not use reserved keywords.  Modules introduced at jdk 9.  Other than that don't think issue is with spotbugs as we run many higher jdks fine.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Yes meant on intellij plugin not spotbugs

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JuditKnoll** [comment]
Closing this, since this is an issue of the [IntelliJ SpotBugs plugin](https://github.com/JetBrains/spotbugs-intellij-plugin) and not spotbugs itself.
