### ISSUE TITLE
ExcludeBaseLineBug files configuration failed.

### ISSUE THREAD

**Issue by RANJEL** [spotbugs/spotbugs#2450]
Product Infos
    SpotBugs: 4.4.2
    IntelliJ SpotBugs plugin: 1.2.5
    IDEA: IntelliJ IDEA 2023.1.2
    IDEA-Build: IU-231.9011.34, May 16, 2023
    JRE: 17.0.6+10-b829.9 amd64
    JVM: OpenJDK 64-Bit Server VM JetBrains s.r.o.

ExcludeBaseLineBug files configuration failed.
org.dom4j.DocumentException: Failing reading \\wsl$\Ubuntu\home\lejnar\Repositories\Memsource\termbase2\excludeFilter.xml
	at edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:279)
	at edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:260)
	at edu.umd.cs.findbugs.ExcludingHashesBugReporter.addToExcludedInstanceHashes(ExcludingHashesBugReporter.java:57)
	at edu.umd.cs.findbugs.ExcludingHashesBugReporter.<init>(ExcludingHashesBugReporter.java:44)
	at edu.umd.cs.findbugs.FindBugs.configureBaselineFilter(FindBugs.java:488)
	at edu.umd.cs.findbugs.FindBugs2.excludeBaselineBugs(FindBugs2.java:409)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.configureFilter(FindBugsStarter.java:452)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.executeImpl(FindBugsStarter.java:320)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStartImpl(FindBugsStarter.java:214)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:191)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:54)
	at org.jetbrains.plugins.spotbugs.core.FindBugsStarter$1.run(FindBugsStarter.java:168)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.dom4j.DocumentException: Sax error while parsing \\wsl$\Ubuntu\home\lejnar\Repositories\Memsource\termbase2\excludeFilter.xml
	at edu.umd.cs.findbugs.SortedBugCollection.doReadXML(SortedBugCollection.java:380)
	at edu.umd.cs.findbugs.SortedBugCollection.doReadXML(SortedBugCollection.java:335)
	at edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:311)
	at edu.umd.cs.findbugs.SortedBugCollection.readXML(SortedBugCollection.java:275)
	... 32 more
Caused by: org.xml.sax.SAXException: Invalid top-level element (expected BugCollection, saw FindBugsFilter)
	at edu.umd.cs.findbugs.SAXBugCollectionHandler.startElement(SAXBugCollectionHandler.java:184)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:731)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1407)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1292)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at edu.umd.cs.findbugs.SortedBugCollection.doReadXML(SortedBugCollection.java:370)
	... 35 more

**Comment by gtoison** [comment]
The issue seems to be caused by using an incorrect filter file:

Caused by: org.dom4j.DocumentException: Sax error while parsing \wsl$\Ubuntu\home\lejnar\Repositories\Memsource\termbase2\excludeFilter.xml

And:

Caused by: org.xml.sax.SAXException: Invalid top-level element (expected BugCollection, saw FindBugsFilter)

Can you please refer to the docs for the expected structure of a filter file?

**Comment by hazendaz** [comment]
Going to close simply because this is spotbugs 4.4.2 and user is trying to use latest intellij, plugin issues from that need to go to intellij.  Do note they are inundated with nonsense tickets at 700+ and do not appear to be addressing anything.

In this case, the stack is as clear as it gets as @gtoison noted, seems invalid usage of filter file but you are just as likely to blow up because you are using too new of stuff for the intellij plugin to work best I can tell from the 100s of tickets regarding intellij.
