### ISSUE TITLE
SAX error in Eclipse while reading exclude filter file

### ISSUE THREAD

**Issue by johnsoneal** [spotbugs/spotbugs#251]
This is the same issue as reported here:
https://sourceforge.net/p/findbugs/bugs/1460/

Eclipse version: Neon through to Oxygen.

Eclipse log:

!ENTRY com.github.spotbugs.plugin.eclipse 4 4 2017-07-08 20:01:19.430
!MESSAGE The following errors occurred during FindBugs analysis:
!SUBENTRY 1 com.github.spotbugs.plugin.eclipse 4 0 2017-07-08 20:01:19.430
!MESSAGE Unable to read filter: /src/config/findbugs/excludes.xml : SAX2 driver class org.apache.xerces.parsers.SAXParser not found
!STACK 0
java.io.IOException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
        at edu.umd.cs.findbugs.filter.Filter.<init>(Filter.java:134)
        at edu.umd.cs.findbugs.FindBugs.configureFilter(FindBugs.java:494)
        at edu.umd.cs.findbugs.FindBugs2.addFilter(FindBugs2.java:374)
        at edu.umd.cs.findbugs.FindBugs2.configureFilters(FindBugs2.java:521)
        at edu.umd.cs.findbugs.FindBugs2.setUserPreferences(FindBugs2.java:475)
        at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:203)
        at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:271)
        at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by johnsoneal** [comment]
Potential additional information for the cause of this issue:

https://issues.jboss.org/browse/WFMP-48?focusedCommentId=13262852&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13262852

**Comment by johnsoneal** [comment]
Can confirm that adding an explicit system property to eclipse ini results in correct behaviour of SpotBugs: 

-Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParse

**Comment by demonfiddler** [comment]
The previous comment should read:
-Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser
