### ISSUE TITLE
Upload of the daily snapshot to gh pages doesn't work

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#308]
See #302 and #304, log file: https://travis-ci.org/spotbugs/spotbugs/builds/262106745

 We fail with: 
```
!!! GitHub Pages support is experimental !!!

travis_fold:end:dpl.1
/home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1386:in `copy': unknown file type: /home/travis/build/spotbugs/spotbugs/eclipsePlugin/build/site/eclipse-daily/. (RuntimeError)
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:471:in `block in copy_entry'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1497:in `call'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1497:in `wrap_traverse'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:468:in `copy_entry'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:443:in `block in cp_r'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/fileutils.rb:442:in `cp_r'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/provider/pages.rb:68:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/provider/pages.rb:67:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.6/gems/dpl-1.8.40/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:22:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.6/bin/dpl:22:in `<main>'
```

**Comment by iloveeclipse** [comment]
`ls $TRAVIS_BUILD_DIR/eclipsePlugin/build/site/eclipse-daily
ls: cannot access /home/travis/build/spotbugs/spotbugs/eclipsePlugin/build/site/eclipse-daily: No such file or directory`

**Comment by iloveeclipse** [comment]
Ok, looks like someone (travis?) deletes the files between `script:` and `after_success` steps, see log below: https://travis-ci.org/spotbugs/spotbugs/builds/262136943?utm_source=github_status&utm_medium=notification.

Looks like `gradlew coveralls` deletes generated files?

**Comment by iloveeclipse** [comment]
At least the coveralls task fails with the error 
```
Caused by: java.io.IOException: Error while analyzing /home/travis/build/spotbugs/spotbugs/spotbugsTestCases/build/classes/java/main/A.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:155)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:130)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:147)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:185)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:218)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:213)
	at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:567)
	at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
	at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
	... 129 more
Caused by: java.lang.IllegalStateException: Can't add different class with same name: A
	at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:107)
	at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:96)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
	at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:98)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:712)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:111)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:127)
	... 136 more
```

**Comment by iloveeclipse** [comment]
OK, after few attempts I've fixed `gradlew coveralls` task but the problem still remains, that after this task all generated site data is lost. WTF???

**Comment by iloveeclipse** [comment]
See PR #310. I have no idea why coveralls deletes data, so I did a workaround.

**Comment by iloveeclipse** [comment]
Finally with PR #311 we fixed deployment and the build!
