### ISSUE TITLE
edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class

### ISSUE THREAD

**Issue by avysk** [spotbugs/spotbugs#3163]
There are multiple issues about that but they all are closed.

When I try to run spotbugs from the command line (not as IDE plugin) it fails in the following way:

```
Exception in thread "main" java.io.IOException: IOException while scanning codebases
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:311)
        at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
        at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
Caused by: edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class
        at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:162)
        at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:282)
        at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:708)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:245)
        ... 4 more
```

Spotbugs 4.8.6 release from here, Oracle JDK 17, Windows 11.

What am I doing wrong?

**Comment by JuditKnoll** [comment]
Can you please share a bit more detail? What command did you use to run SpotBugs?

**Comment by avysk** [comment]
Sure. `java -jar <path to>\spotbugs.jar -textui <path to java file>`.

Thanks for looking at my issue!

**Comment by avysk** [comment]
It is taken from [here](https://spotbugs.readthedocs.io/en/stable/running.html).

**Comment by JuditKnoll** [comment]
SpotBugs can only handle compiled files. You need to compile the files first and give the path of the jar or the class files.

**Comment by hazendaz** [comment]
Maybe we could give a better error message? This type of ticket gets opened frequently it seems and it should be fairly easy to output the probable cause in the message.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
