### ISSUE TITLE
Gradle deprecation error in Travis build

### ISSUE THREAD

**Issue by javabeanz** [spotbugs/spotbugs#341]
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

	at org.gradle.api.internal.tasks.DefaultSourceSetOutput.getClassesDir(DefaultSourceSetOutput.java:80)

	at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getClassesDir(Unknown Source)

	at org.sonarqube.gradle.SonarQubePlugin.configureSourceDirsAndJavaClasspath(SonarQubePlugin.java:169)

	at org.sonarqube.gradle.SonarQubePlugin.lambda$configureForJava$1(SonarQubePlugin.java:104)

	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)

	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)

	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)

	at org.sonarqube.gradle.SonarQubePlugin.configureForJava(SonarQubePlugin.java:103)

	at org.sonarqube.gradle.SonarQubePlugin.addGradleDefaults(SonarQubePlugin.java:434)

	at org.sonarqube.gradle.SonarQubePlugin.computeSonarProperties(SonarQubePlugin.java:382)

	at org.sonarqube.gradle.SonarQubePlugin.lambda$createTask$10(SonarQubePlugin.java:344)

	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:432)

**Comment by KengoTODA** [comment]
Thanks for your report. This is deprecated with #320 #337 #299, let me close it.
