### ISSUE TITLE
Errors on creating markers in Eclipse

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#385]
Since I've enabled SpotBugs on SpotBugs, I see many of those errors in the Eclipse log:
```
Java Model Exception: Java Model Status [this$1 [in MainFrameComponentFactory [in MainFrameComponentFactory.java [in edu.umd.cs.findbugs.gui2 [in src/gui [in spotbugs-spotbugs]]]]] does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:556)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:590)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Member.getNameRange(Member.java:343)
	at de.tobject.findbugs.reporter.MarkerUtil.completeFieldInfo(MarkerUtil.java:350)
	at de.tobject.findbugs.reporter.MarkerUtil.getJavaElement(MarkerUtil.java:331)
	at de.tobject.findbugs.reporter.MarkerUtil.createMarkerParameter(MarkerUtil.java:181)
	at de.tobject.findbugs.reporter.MarkerUtil.createBugParameters(MarkerUtil.java:169)
	at de.tobject.findbugs.reporter.MarkerUtil.createMarkers(MarkerUtil.java:123)
	at de.tobject.findbugs.builder.FindBugsWorker.updateBugCollection(FindBugsWorker.java:357)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:227)
	at de.tobject.findbugs.builder.FindBugsBuilder$StartedFromBuilderJob.runWithProgress(FindBugsBuilder.java:214)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Not sure yet if this is a SpotBugs regression or some Eclipse 4.8 issue (I'm running 4.8 M2)

**Comment by iloveeclipse** [comment]
This seem to be related to the serializable detector.
Example code:
```
package ghIssues;

import javax.swing.JSplitPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

public class Issue385 {
    void removeSplitPaneBorders(JSplitPane pane) {
        pane.setUI(new BasicSplitPaneUI() {
            @Override
            public BasicSplitPaneDivider createDefaultDivider() {
                return new BasicSplitPaneDivider(this) {
                    @Override
                    public void setBorder(Border b) {
                    }
                };
            }
        });
        pane.setBorder(new EmptyBorder(3, 3, 3, 3));
    }
}
```

**Comment by krallus** [comment]
Has the detector for SE_BAD_FIELD been removed from SpotBugs?  I don't see it anymore.  FindBugs was the only code analyzer I've personally used that would warn about non-serializable fields in serializable classes.
