### ISSUE TITLE
SpotBugs is not handling module-info.class

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/spotbugs#408]
SpotBugs will crash when a new module-info class is scanned.
```
java.lang.RuntimeException: java.io.IOException: IOException while scanning codebases: Invalid classfile format in /var/lib/jenkins/jobs/Citizen-Intelligence-Agency-Complete-site-sonar-report/workspace/service.api/target/classes/module-info.class
```

For more info:
https://github.com/SonarQubeCommunity/sonar-findbugs/issues/139

**Comment by KengoTODA** [comment]
which version reproduced this issue? If it's RC4 (used by sonar-findbugs 3.6.0), RC6 might be solution.

**Comment by iloveeclipse** [comment]
https://github.com/SonarQubeCommunity/sonar-findbugs/issues/139 is closed/fixed, new SpotBugs version works.

**Comment by KengoTODA** [comment]
> SonarQubeCommunity/sonar-findbugs#139 is closed/fixed

It is because of sonar-findbugs' temporal fix:
https://github.com/SonarQubeCommunity/sonar-findbugs/pull/141/files

So I guess we need to keep this issue opened?

**Comment by h3xstream** [comment]
Thanks for the info.

**Comment by miyakawataku** [comment]
I got the same error. The next project is a minimum source set to reproduce the issue, using SpotBugs 3.1.0-RC7 and the Gradle plugin 1.5.

* https://github.com/miyakawataku/reproduce-spotbugs-bug-with-module-info

The spotbugsMain task produces the following stacktrace.

```
$ ./gradlew spotbugsMain --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotbugsMain'.
> java.io.IOException: IOException while scanning codebases

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spotbugsMain'.
...
... (snip) ...
...
Caused by: edu.umd.cs.findbugs.classfile.InvalidClassFileFormatException: Invalid classfile format in /home/taku/pj/reproduce-spotbugs-bug-with-module-info/build/classes/java/main/module-info.class
        at edu.umd.cs.findbugs.classfile.engine.ClassParser.readConstant(ClassParser.java:244)
        at edu.umd.cs.findbugs.classfile.engine.ClassParser.parse(ClassParser.java:101)
        at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBase.getClassDescriptor(SingleFileCodeBase.java:269)
        at edu.umd.cs.findbugs.classfile.impl.SingleFileCodeBaseEntry.getClassDescriptor(SingleFileCodeBaseEntry.java:82)
        at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:259)
        at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:674)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:215)
        ... 17 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by iloveeclipse** [comment]
I can reproduce. We don't have updated constant pool map, see https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.4 and edu.umd.cs.findbugs.classfile.engine.ClassParser.CONSTANT_FORMAT_MAP.

Probably an easy fix, but let see if we can get it into 3.1.0.

**Comment by iloveeclipse** [comment]
Fixing ClassParser is not enough, next issue in ClassParserUsingASM.parse has same issue and after fixing this one I finally get:
```
java.lang.RuntimeException: Unable to parse classfile for module-info
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:70)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:1)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.classfile.engine.bcel.ClassContextClassAnalysisEngine.analyze(ClassContextClassAnalysisEngine.java:49)
	at edu.umd.cs.findbugs.classfile.engine.bcel.ClassContextClassAnalysisEngine.analyze(ClassContextClassAnalysisEngine.java:1)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.AnalysisContext.isTooBig(AnalysisContext.java:482)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1053)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:313)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:219)
	at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:275)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.bcel.classfile.Constant.readConstant(Constant.java:167)
	at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:66)
	at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:239)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:144)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:58)
	... 13 more
```
We should completely remove that f... module-info crap from scanning! I hate the date they decided to put module info into the binary format.

**Comment by iloveeclipse** [comment]
@mebigfatguy : do you have an idea where is the best entry point for excluding files from analysis, as early as possible?
