### ISSUE TITLE
Launching SpotBugs GUI on macOS triggers exception

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#418]
When we launch SpotBugs GUI on Java 9 for macOS, it prints error because SpotBugs is using method which is deleted already. This bug does not affect to SpotBugs features, so it's not so severe. Java 8 has no problem like this.

Maybe we can refer javadoc at [here](https://coderanch.com/how-to/javadoc/appledoc/api/com/apple/eawt/Application.html).

```
Exception while loading the OSXAdapter: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at edu.umd.cs.findbugs.gui2.MainFrameMenu.initOSX(MainFrameMenu.java:564)
	at edu.umd.cs.findbugs.gui2.MainFrameComponentFactory$InitializeGUI.setupOSX(MainFrameComponentFactory.java:434)
	at edu.umd.cs.findbugs.gui2.MainFrameComponentFactory$InitializeGUI.run(MainFrameComponentFactory.java:406)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchMethodError: com.apple.eawt.Application.addApplicationListener(Lcom/apple/eawt/ApplicationListener;)V
	at edu.umd.cs.findbugs.gui2.OSXAdapter.registerMacOSXApplication(OSXAdapter.java:110)
	... 21 more
```

**Comment by KengoTODA** [comment]
https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-C86F7403-7D7C-456F-8873-18C7F1BEDE2F

**Comment by Spatrik95** [comment]
The SpotBugs catch this exception and only log an error message on the console output:

```
This version of Mac OS X does not support the Apple EAWT. Application Menu handling has been disabled (java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationAdapter)
```

The only effect of this is that the menubar is not filled with menu items on the MacOS dock panel, just in the application window, but all of them work correctly.
