### ISSUE TITLE
Maven plugin spot-bugs leads to mvn incompatibilities in other plugins

### ISSUE THREAD

**Issue by blasd** [spotbugs/spotbugs#521]
Hello,

According to spot-bugs maven plugin, Spotbugs is compatible with

    <prerequisites>
      <maven>3.0.1</maven>
    </prerequisites>

However, it seems the use of <artifactId>maven-core</artifactId> in 3.5.2 leads to incompatibilities in other plugins when run in an older maven version (e.g. mvn 3.2.5 and mvn 3.3.9).

In https://github.com/blasd/spotbugs, you will find a sample maven project based on mvn-deploy-plugin 2.8.2 which fails during mvn deploy target (in the sample project, `mvn deploy` will deploy in a local folder). Reming the spotbugs from `<plugins>` enables deployment.
 
To reproduce the issue:

1. clone the fork, 
2. cd exampleProject
3. run `mvn deploy`

It shall fail under mvn 3.3 and 3.2, and certainly previous versions (as prerequisites suggests compatibility up to 3.0)

	$ mvn --version
	Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
	Maven home: C:\Users\blacelle112212\Downloads\apache-maven-3.3.9
	Java version: 1.8.0_152, vendor: Oracle Corporation
	Java home: C:\HOMEWARE\Install\jdk-8u152-windows-x64\jre
	Default locale: en_US, platform encoding: Cp1252
	OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

The issue looks like:

	[INFO] --- maven-install-plugin:2.4:install (default-install) @ sampleProject ---
	ve[WARNING] Error injecting: org.apache.maven.artifact.installer.DefaultArtifactInstaller
	com.google.inject.ProvisionException: Unable to provision, see the following errors:
	
	1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
	  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
	  while locating java.lang.Object annotated with *
	  at org.eclipse.sisu.wire.LocatorWiring
	  while locating org.eclipse.aether.impl.VersionRangeResolver
	    for parameter 2 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.<init>(Unknown Source)
	  while locating org.eclipse.aether.internal.impl.DefaultDependencyCollector
	  while locating java.lang.Object annotated with *
	  at org.eclipse.sisu.wire.LocatorWiring
	  while locating org.eclipse.aether.impl.DependencyCollector
	    for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
	  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
	  while locating java.lang.Object annotated with *
	  while locating org.apache.maven.artifact.installer.DefaultArtifactInstaller
	Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
	        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	        at java.lang.reflect.Field.set(Field.java:764)
	        at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
	        at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
	        at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
	        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
	        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	        at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)

Given the stack, it appears the issue may also appear in the install plugin (maven-install-plugin:2.4), in my original project, the issue is with mvn deploy plugin 2.8.2

**Comment by KengoTODA** [comment]
Hi, could you issue at another repository https://github.com/spotbugs/spotbugs-maven-plugin which manages maven plugin development?
Thanks in advance.

**Comment by blasd** [comment]
Done. Thanks

**Comment by blasd** [comment]
https://github.com/spotbugs/spotbugs-maven-plugin/issues/21
