### ISSUE TITLE
Error on lambda analysis: "Constant pool at index 0 is null."

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs#547]
Spotbugs 3.1.0 or also latest from master reports analysis error on following code:
```
package ghIssues;
import java.util.List;
public class X {
    static boolean doSomething(List<String> dups) {
        return dups.stream().anyMatch(x -> x.isEmpty());
    }
}
```

Stack:
```
org.apache.bcel.classfile.ClassFormatException: Constant pool at index 0 is null.
	at org.apache.bcel.classfile.ConstantPool.getConstant(ConstantPool.java:258)
	at org.apache.bcel.classfile.ConstantPool.getConstantString(ConstantPool.java:293)
	at edu.umd.cs.findbugs.detect.ResolveAllReferences.getClassName(ResolveAllReferences.java:101)
	at edu.umd.cs.findbugs.detect.ResolveAllReferences.visit(ResolveAllReferences.java:155)
	at edu.umd.cs.findbugs.visitclass.BetterVisitor.visitJavaClass(BetterVisitor.java:321)
	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.setupVisitorForClass(PreorderVisitor.java:433)
	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:375)
	at org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
	at edu.umd.cs.findbugs.detect.ResolveAllReferences.visitClassContext(ResolveAllReferences.java:74)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1079)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:313)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:219)
	at de.tobject.findbugs.builder.FindBugsBuilder$StartedFromBuilderJob.runWithProgress(FindBugsBuilder.java:212)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by iloveeclipse** [comment]
Looks like `org.apache.bcel.classfile.ConstantInvokeDynamic` instances generated by BCEL contain garbage. The "class_index" is `0` but neither BCEL itself nor javap show anything in the constant pool at index `0`.
