### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by huangshiyou** [spotbugs/spotbugs#669]
I use ./gradlew build to build the project. When I tried to run the program using the following command from the root directory of the source code:
```
java -jar ./spotbugs/build/lib/spotbugs.jar -textui ShowHelp
```
./spotbugs/build/lib this directory contains all the necessary jars as follows:
![screen shot 2018-06-14 at 4 14 35 pm](https://user-images.githubusercontent.com/7650529/41442839-2070225a-6fee-11e8-94a7-1fb94a508c9a.png)

It reports the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/tree/ClassNode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at edu.umd.cs.findbugs.PluginLoader.loadPluginComponents(PluginLoader.java:837)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:397)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1479)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1433)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:150)
	at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:351)
	at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:77)
	at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:60)
	at edu.umd.cs.findbugs.FindBugs2.<clinit>(FindBugs2.java:86)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.ClassNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Any suggestions on this issue? Thanks!

**Comment by pzygielo** [comment]
See #575.

**Comment by ThrawnCA** [comment]
Having those jars in the directory isn't enough by itself. You need to add them to your classpath with the -cp option.

**Comment by huangshiyou** [comment]
@pzygielo I will try that. I think this really needs to be documented. 
@ThrawnCA I added jar files to the classpath, still the same problem.
