### ISSUE TITLE
Potential NPE in test-harness-core

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#671]
When run JUnit test with test-harness-core, we may face following NPE:

```
java.lang.NullPointerException: Cannot suppress a null exception.
	at java.lang.Throwable.addSuppressed(Throwable.java:1046)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at edu.umd.cs.findbugs.test.AnalysisRunner.run(AnalysisRunner.java:114)
	at edu.umd.cs.findbugs.test.SpotBugsRule.performAnalysis(SpotBugsRule.java:89)
```

We need to filter like below, or consider to use `error` itself instead of its cause.

```patch
diff --git a/test-harness-core/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java b/test-harness-core/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java
index 51d3bf3ab..3f389d991 100644
--- a/test-harness-core/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java
+++ b/test-harness-core/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java
@@ -111,6 +111,7 @@ public class AnalysisRunner {
                 AssertionError assertionError = new AssertionError(
                         "Analysis failed with exception. Check stderr for detail.");
                 bugReporter.getQueuedErrors().stream().map(error -> error.getCause())
+                        .filter(Objects::nonNull)
                         .forEach(assertionError::addSuppressed);
                 throw assertionError;
             }
```

**Comment by KengoTODA** [comment]
Here the `getQueuedErrors()` returns not `java.lang.Error` but `edu.umd.cs.findbugs.AbstractBugReporter.Error` :face_with_head_bandage: this is why we filter to suppress.

Maybe we can use `bugReporter.reportQueuedErrors()` instead.
