### ISSUE TITLE
'Finding bugs in Project_1...' has encountered a problem.

### ISSUE THREAD

**Issue by TheRealAyCe** [spotbugs/spotbugs#678]
Using Eclipse IDE for Java Developers Photon (4.8.0) on Java 10.

When I try to "Find Bugs" with the plugin on any project an error dialog box opens and displays:

---

'Finding bugs in Project_1...' has encountered a problem.

An internal error occurred during: 'Finding bugs in Project_1...'

---

And this is logged in the workspace log file:

```
!ENTRY org.eclipse.core.jobs 4 2 2018-07-01 08:33:58.974
!MESSAGE An internal error occurred during: "Finding bugs in Project_1...".
!STACK 0
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
	at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:970)
	at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:876)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:222)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:313)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:219)
	at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:275)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by iloveeclipse** [comment]
Which SpotBugs version? Can you reduce the problem to a specific code example? I guess some bytecode from Java 10 can't be read, or even we don't accept entire class.

**Comment by TheRealAyCe** [comment]
Hi, looking in Eclipse Installation Details the SpotBugs version seems to be:
  SpotBugs	3.1.2.r201802250230-59118d9	com.github.spotbugs.plugin.eclipse.feature.group	SpotBugs Project

I configured my workspace to use compiler level 1.8 only across all projects. The problem occurrs even when trying to scan an empty new project (tested with workspace settings and with manual "Java 10"-level settings).

**Comment by KengoTODA** [comment]
@iloveeclipse if there is a way to automate upgrading version at marketplace, let me know then I'll integrate it with Travis CI build.

**Comment by iloveeclipse** [comment]
@KengoTODA : I'm not aware about automated updates on marketplace.
