### ISSUE TITLE
ConcurrentModificationException in eclipse

### ISSUE THREAD

**Issue by rahimalizada** [spotbugs/spotbugs#681]
When running the plugin in eclipse on multiple (4+) projects simultaneously sometimes the following exception is thrown:

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.report(OverlyPermissiveMethod.java:260)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.finishPass(DetectorToDetector2Adapter.java:55)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1115)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:313)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:219)
	at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:275)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

Since it is happening in eclipse plugin I am reporting it here and not in fbcontrib

**Comment by iloveeclipse** [comment]
Please report to the fb-contrib http://fb-contrib.sourceforge.net/ tracker.
