### ISSUE TITLE
Spotbugs 3.1.6 fails on JDK 11

### ISSUE THREAD

**Issue by guw** [spotbugs/spotbugs#711]
I have a multi-JDK build configured.
https://github.com/eclipse/ebr/blob/master/.travis.yml

Spotbugs 3.1.5 runs fine on OpenJDK 8 and 10 but fails on 11 
https://travis-ci.org/eclipse/ebr/jobs/405750075

```
11:00:05:251 [INFO] --- spotbugs-maven-plugin:3.1.5:spotbugs (spotbugs) @ ebr-maven-shared ---
11:00:05:708 [INFO] Fork Value is true
     [java] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
     [java] The following errors occurred during analysis:
     [java]   Unable to get XClass for java/lang/Integer
     [java]     java.lang.UnsupportedOperationException
     [java]       At org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
     [java]       At org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:519)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:703)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:79)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
...

```

**Comment by iloveeclipse** [comment]
Gunnar, please try 3.1.6.

**Comment by guw** [comment]
Same problem on 3.1.6.
https://travis-ci.org/eclipse/ebr/jobs/408871424

**Comment by iloveeclipse** [comment]
Mist.

**Comment by iloveeclipse** [comment]
Gunnar, are you sure you use right ASM version? My IDE says that the reported lines are not valid in ClassVisitor.

**Comment by guw** [comment]
@iloveeclipse I don't force a specific ASM version. I was expecting Maven to download the correct one. It seems that it picked 6.2. Is this the right one?

```
Downloaded from central: https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.6/spotbugs-3.1.6.pom (5.0 kB at 454 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.pom
Progress (1): 2.3/2.9 kB
Progress (1): 2.9 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.pom (2.9 kB at 587 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/ow2/1.5/ow2-1.5.pom
Progress (1): 2.3/11 kB
Progress (1): 5.0/11 kB
Progress (1): 7.8/11 kB
Progress (1): 11/11 kB 
Progress (1): 11 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/ow2/1.5/ow2-1.5.pom (11 kB at 2.2 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.2/asm-analysis-6.2.pom
Progress (1): 2.3/3.2 kB
Progress (1): 3.2 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.2/asm-analysis-6.2.pom (3.2 kB at 394 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.pom
Progress (1): 2.3/3.1 kB
Progress (1): 3.1 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.pom (3.1 kB at 520 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.pom
Progress (1): 2.3/3.7 kB
Progress (1): 3.7 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.pom (3.7 kB at 610 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.2/asm-util-6.2.pom
Progress (1): 2.3/3.6 kB
Progress (1): 3.6 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.2/asm-util-6.2.pom (3.6 kB at 607 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-xml/6.2/asm-xml-6.2.pom
Progress (1): 2.3/3.3 kB
Progress (1): 3.3 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-xml/6.2/asm-xml-6.2.pom (3.3 kB at 366 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/bcel/bcel/6.2/bcel-6.2.pom
```

**Comment by muminc** [comment]
Tested locally,  with

Opcodes.ASM6

Running on Java 11, I got failures with same stacktrace as @guw 

Changed  to

Opcodes.ASM7_EXPERIMENTAL;

and spotbugs runs ok on Java 11

**Comment by fdesu** [comment]
@muminc 
You're right on that. Following the stacktrace, that piece throws an exception:
```java
  public void visitNestMemberExperimental(final String nestMember) {
    if (api < Opcodes.ASM7_EXPERIMENTAL) {
      throw new UnsupportedOperationException();
    }
   ...
```
so an API usage should be adjusted.

**Comment by Paladinium** [comment]
@iloveeclipse , @KengoTODA , @daveho : any chance to release 3.1.7 soon to get the fix that @muminc made? I think Spotbugs-Users would highly appreciate Java 11 Support!

**Comment by KengoTODA** [comment]
Today 3.1.7 has been released, please check.

* https://github.com/spotbugs/spotbugs/releases/tag/3.1.7

Maven central may needs several hours to host .jar file.

**Comment by wrprice** [comment]
@KengoTODA was the publish successful?  18 hours later, not yet on Central, FYI.

**Comment by karussell** [comment]
Thanks for this. And can confirm that this [fixed the issue](https://travis-ci.org/graphhopper/graphhopper/jobs/428534219)! (see the required [minor change](https://github.com/graphhopper/graphhopper/commit/1b648327bc8dae41f1fff5129b99f3e670a22d62) for the maven plugin)

**Comment by perlun** [comment]
Works for me also, thanks a lot @KengoTODA and @muminc. I think we could close this now.

**Comment by guw** [comment]
Still not available in Maven Central.

**Comment by KengoTODA** [comment]
> Still not available in Maven Central.

Hi @guw, can you access [this URL](https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.7/)?

**Comment by guw** [comment]
@KengoTODA I'm confused. I thought you released 3.1.7 of the Spotbugs Maven Plug-in.
`https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/`

Will 3.1.6 version of the Maven plug-in use 3.1.7 of Spotbugs?

**Comment by karussell** [comment]
This issue is about the library not the plugin. Therefor I made this comment:

> (see the required [minor change](https://github.com/graphhopper/graphhopper/commit/1b648327bc8dae41f1fff5129b99f3e670a22d62) for the maven plugin)

**Comment by KengoTODA** [comment]
@guw to use latest SpotBugs version, you need to set the version explicitly in pom.xml, for example:

https://spotbugs.readthedocs.io/en/stable/maven.html

@karussell thanks for your share!

**Comment by guw** [comment]
@KengoTODA When I reported the issue - I was using the Maven plug-in. Thus, I opened the issue with the expectation to have a fix deliver for the Maven plug-in. I'm not sure where in the process this has been converted to a non-Maven plug-in issue. 

I don't like to introduce hard coded dependency versions in a Maven plug-in. This causes maintenance costs down the road. Can you please also release a new version of the Maven plug-in?

**Comment by karussell** [comment]
> I'm not sure where in the process this has been converted to a non-Maven plug-in issue.

different issue list: https://github.com/spotbugs/spotbugs-maven-plugin/issues

**Comment by markathomas** [comment]
Not sure if this is a library issue or a plugin issue, but running with maven and Java 11 gives me the following every time:
```
[INFO] --- spotbugs-maven-plugin:3.1.6:spotbugs (spotbugs) @ boxview ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/mthomas/.m2/repository/org/codehaus/groovy/groovy/3.0.0-alpha-3/groovy-3.0.0-alpha-3.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Fork Value is true
     [java] Exception in thread "main" java.lang.RuntimeException: Could not instantiate edu.umd.cs.findbugs.detect.BuildObligationPolicyDatabase as Detector2
     [java] 	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:95)
     [java] 	at edu.umd.cs.findbugs.DetectorFactory.createDetector2(DetectorFactory.java:397)
     [java] 	at edu.umd.cs.findbugs.plan.AnalysisPass.instantiateDetector2sInPass(AnalysisPass.java:132)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:992)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
     [java] Caused by: java.lang.reflect.InvocationTargetException
     [java] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
     [java] 	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:93)
     [java] 	... 6 more
     [java] Caused by: java.lang.NoClassDefFoundError: javax/annotation/WillClose
     [java] 	at edu.umd.cs.findbugs.detect.BuildObligationPolicyDatabase.<init>(BuildObligationPolicyDatabase.java:134)
     [java] 	... 11 more
     [java] Caused by: java.lang.ClassNotFoundException: javax.annotation.WillClose
     [java] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
     [java] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
     [java] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
     [java] 	... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I tried adding `jsr305.jar` to both my classpath and the plugin dependencies but continue to receive this error.  Any suggestions?

**Comment by javydreamercsw** [comment]
@markathomas tried on 3.1.7?

**Comment by markathomas** [comment]
yes, this is what my pom looks like:
```
<plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>3.1.6</version>
                <dependencies>
                    <dependency>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs</artifactId>
                        <version>3.1.7</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.code.findbugs</groupId>
                        <artifactId>jsr305</artifactId>
                        <version>3.0.2</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>spotbugs-check</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
