### ISSUE TITLE
Version 3.1.9 stdout spam when network is blocked

### ISSUE THREAD

**Issue by risomt** [spotbugs/spotbugs#842]
We recently tried to update to spotbugs 3.1.9 and ran into the following message when running spotbugs in a docker container with restricted (no) network access. The message is:

```
<docker container>:/$ spotbugs -textui -progress tmp/Main.class
2018-12-28 21:28:25,965 main ERROR Could not determine local host name java.net.UnknownHostException: 7759bb55edb9: 7759bb55edb9: Temporary failure in name resolution
    at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
    at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:53)
    at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
    at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
    at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
    at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:121)
    at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:49)
    at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
    at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:355)
    at edu.umd.cs.findbugs.Version.<clinit>(Version.java:38)
    at edu.umd.cs.findbugs.Plugin.<init>(Plugin.java:119)
    at edu.umd.cs.findbugs.PluginLoader.constructMinimalPlugin(PluginLoader.java:1114)
    at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:715)
    at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:396)
    at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1479)
    at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1433)
    at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:150)
    at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:351)
    at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:77)
    at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:60)
    at edu.umd.cs.findbugs.FindBugs2.<clinit>(FindBugs2.java:86)
Caused by: java.net.UnknownHostException: 7759bb55edb9: Temporary failure in name resolution
    at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
    at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
    at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
    at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637)
    ... 25 more

Scanning archives (1 / 1)
2 analysis passes to perform
Pass 1: Analyzing classes (11 / 11) - 100% complete
Pass 2: Analyzing classes (1 / 1) - 100% complete
Done with analysis

<docker container>:/$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing)
```

The docker image is built with:

```
FROM ubuntu:16.04

ENV LANG C.UTF-8

RUN apt-get update                                              && \
    apt-get install -y                                             \
        curl                                                       \
        software-properties-common                              && \
    add-apt-repository ppa:openjdk-r/ppa                        && \
    apt-get update                                              && \
    apt-get install -y --no-install-recommends                     \
        openjdk-11-jdk-headless

RUN curl -fSLO "https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.9/spotbugs-3.1.9.tgz"    && \
    tar -xzf spotbugs-3.1.9.tgz                                                                                 && \
    cp -R /spotbugs-3.1.9 /usr/local/lib/                                                                       && \
    ln -s /usr/local/lib/spotbugs-3.1.9/bin/spotbugs /usr/local/bin/spotbugs                                    && \
    rm -rf /spotbugs-3.1.9                                                                                      && \
    rm spotbugs-3.1.9.tgz
```

And then started through: `docker run -it --network none --rm java:11 bash`.

From other bugs and the stack trace of the error message it appears to be related to the introduction pf SLF4J / LOG4J and may be related to https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java#L537. 

Reverting to version 3.1.8 avoided the issue.

It certainly appears to be a third party issue, but maybe there's an easy fix to suppress it somehow.

**Comment by kevin-wayne** [comment]
Any work-around? I encounter the same messages when using with a Docker container which runs with no network access. I don't think I have any control over the SLF4J logger configuration. I can confirm that, if the Docker container is run with network access, everything works just fine.

**Comment by Samikya** [comment]
Is there a Dockerfile/Docker image for spotbugs ?

**Comment by SarayuR** [comment]
Is there a dockerfile to build spotbugs image and a docker command to initiate scans ?

**Comment by hazendaz** [comment]
closing as 5 years old, actual issue is in log4j2.  in last 5 years both loggers slfj4 or logj2 have changed a lot.  If still an issue with most recent copies, then please reopen with new data indicating newer versions.  Ultimately though, these are not likely to be opened here but rather something to look at either log4j2 (issue here) or slf4j for help.
