### ISSUE TITLE
Issue in Eclipse

### ISSUE THREAD

**Issue by Dichotomia** [spotbugs/spotbugs#984]
![image](https://user-images.githubusercontent.com/5593198/60280704-c294e400-9903-11e9-9b55-d80e55c6475d.png)
![image](https://user-images.githubusercontent.com/5593198/60280905-2a4b2f00-9904-11e9-8b54-359ffce38db9.png)

**Comment by iloveeclipse** [comment]
Would you please attach the error log *as text* here? Thanks.

**Comment by Dichotomia** [comment]
An internal error occurred during: "Finding bugs in mac-bc360-custom...".

java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:360)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:237)
	at de.tobject.findbugs.FindbugsPlugin.logMessage(FindbugsPlugin.java:591)
	at de.tobject.findbugs.FindbugsPlugin.logException(FindbugsPlugin.java:549)
	at de.tobject.findbugs.builder.FindBugsWorker.updateBugCollection(FindBugsWorker.java:352)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:227)
	at de.tobject.findbugs.builder.FindBugsBuilder$StartedFromBuilderJob.runWithProgress(FindBugsBuilder.java:219)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=4.12.0.I20190605-1800
java.version=1.8.0_212
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by iloveeclipse** [comment]
Interesting. In 4.12 Eclipse you can't get NPE at this line, except the JVM did something really weird with the code.

Is this always reproducible? If yes, can you please try to use OpenJDK or Oracle one?

**Comment by Dichotomia** [comment]
I had uninstalled the plugin because it didn't work anymore. So i cannot reproduce it. I think to switch to Openjdk build by a adoptopenjdk
