### ISSUE TITLE
Adding typescript-generator classpath breaks spotbugs

### ISSUE THREAD

**Issue by olegshtch** [spotbugs/spotbugs#992]
Somehow typescript-generator classpath causes spotbugs to break:

```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:62757'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:93)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:263)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException:      
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:148)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:80)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:63)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:80)
	... 7 more
Caused by: java.io.IOException:      
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:190)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	... 13 more
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:62757'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:135)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException:      
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:273)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:261)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:255)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:133)
	... 7 more
> Task :spotbugsMain FAILED
```

build.gradle:
```groovy
buildscript {
	repositories {
		maven {
			url 'https://plugins.gradle.org/m2/'
		}
	}
	dependencies {
		classpath 'gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:2.0.0'
		// uncomment this to break spotbugsMain:
		// classpath 'cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.15.527'
	}
}

apply plugin: 'application'
apply plugin: 'java'
apply plugin: "com.github.spotbugs"

description = 'test'
group = 'org.test'

mainClassName = 'org.test.testgradle1.Main'

repositories {
    jcenter()
}

dependencies {
    testCompile 'junit:junit:4.12'
}
```

Copy https://github.com/vojtechhabarta/typescript-generator/issues/387

**Comment by olegshtch** [comment]
[gradle.log](https://github.com/spotbugs/spotbugs/files/3410071/gradle.log)

**Comment by olegshtch** [comment]
Forgot to mention I fixed by adding excluding old dependencies:

```groovy
		classpath ('cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.15.527') {
			exclude group: 'org.gradle',  module: 'gradle-core'
			exclude group: 'org.gradle',  module: 'gradle-base-services'
			exclude group: 'org.gradle',  module: 'gradle-base-services-groovy'
			exclude group: 'org.codehaus.groovy',  module: 'groovy-all'
		}
```
